bug: Only query Cinder API if volume size > 0
Only query Cinder API for volume type if volume size is greater than 0.
This is to make sure that Magnum does not have a hard dependency on
Cinder and works without the Cinder API enlisted as an endpoint.

This regression was introduced in https://review.opendev.org/#/c/621734/
where boot from volume support was introduced. See
https://storyboard.openstack.org/#!/story/2005386#comment-147555 for
more details of the error.

Story: 2005386
Task: 37565

(cherry picked from commit 26a171f951cb40809d378af82433dbe28f16cdf2)

bug: cluster creation without docker_volume_size

Allows cluster to be created without docker_volume_size where we were
previously seeing this error:

    TypeError: int() argument must be a string,
    a bytes-like object or a number, not 'NoneType'

Regression introduced in https://review.opendev.org/#/c/695239/.

Story: 2005386
Task: 37565

(cherry picked from commit 612b2277769e8e4ac490925c9e01a89cb6b1cb11)

Change-Id: I1bdec0c11a18bea9143fb4792a0a2e4ba5dc1fcf