Fix the content of 'discovery_endpoint' not show up in exception
When failed to get discovery url, magnum returns:
$ magnum bay-create --name swarmbay --baymodel swarmbaymodel --node-count 3
ERROR: Fail to get discovery url from %(discovery_endpoint) (HTTP 500)

where %(discovery_endpoint) should be replaced by the actual discovery_endpoint, like below:
$ magnum bay-create --name swarmbay --baymodel swarmbaymodel --node-count 3
ERROR: Failed to get discovery url from 'https://discovery.etcd.io/new?size=1'. (HTTP 500)
also: Fail -> Failed

Change-Id: I68f85af33ff30227bae19ac0da588b942c7c189d
Closes-Bug: #1531725