Remove circle reference
We can not import magnum.api.validation because of circle reference.

We can reproduce this bug by "tox -egenconfig" or importing
magnum.api.validation in a python console.

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "magnum/api/validation.py", line 20, in <module>
    from magnum.api.controllers.v1 import utils as api_utils
  File "magnum/api/controllers/v1/__init__.py", line 30, in <module>
    from magnum.api.controllers.v1 import baymodel
  File "magnum/api/controllers/v1/baymodel.py", line 29, in <module>
    from magnum.api import validation
ImportError: cannot import name validation

Change-Id: Ib73d7f1d989b9bc860bfadafa52e9a83996f5de9
Closes-Bug: #1521840