Fix misquoted comment
Seen while validating release, in the heat container agent journal:

```
/var/lib/heat-config/heat-config-script/0c399610-30a6-4728-80f2-702b0630400f:
    line 776: --cluster-cidr: command not found
error: expected 'logs [-f] [-p] (POD | TYPE/NAME) [-c CONTAINER]'.
```

Task: 41231
Story: 2008330
Change-Id: I3fdd186b73950b4b3e5790752eaafc47ff7da8f3
(cherry picked from commit 9adfc4430919b0d7ad7a8a27175bc3357b881d4e)