Fix for enum type docker_storage_driver
Create enum type "docker_storage_driver" for migration

This is fixing
   oslo_db.exception.DBError: (psycopg2.ProgrammingError) type
   "docker_storage_driver" does not exist

Closes-Bug: #1609776

Change-Id: I92d427e90bd73b4114d8688d3761cabac450fc9d