Fix oslo policy file genrator tool for Magnum
oslo tool to generate the policy or sample policy file does not work for magnum service.

``oslopolicy-policy-generator --namespace magnum``  end up with
below error:
    ModuleNotFoundError: No module named 'magnum.policy'

same error with oslopolicy-sample-generator --namespace magnum

oslo.policy policy generator tool look for the service oslo policy enforcer
entry and does not find it. setup.cfg file is missing the entry point for
magnum oslo policy enforcer.

- https://lists.openstack.org/archives/list/openstack-discuss@lists.openstack.org/thread/5ZRWWL3YKWX3XCFGTC4G2KP6PCJMBL64/

Closes-Bug: #2068519
Change-Id: Iff94f7dea491b0ea465b17cd60c37423224f9ffa
(cherry picked from commit 8d09169a8aa4d8425e9ab7f37bbb636c4410a39f)