Use exception.faultstring instead of exception.message
Use more compatibale way. Othterwise, in python3, it will report error:
b"AttributeError: 'ClientSideError' object has no attribute 'message'"

Partially-Implements: blueprint magnum-python3

Change-Id: I3c3cd4e1d7bd458a3c8b53186dc852b21c477583