Do not inspect contianer doesn't exist.
Currently, magnum will create a container object first and save it in magnum
DB, but in some cases it will fail to start in docker cluster. Later when
call container_show, _find_container_by_name will return {}, with {} to
inspect docker instance, docker client will raise an exception:

NullResource: image or container param is undefined.

it will cause magnum api raise an internal Error:
ERROR: Docker internal Error: image or container param is undefined (HTTP 500)

This patch checks _find_container_by_name return value before passing
inspect_container() to avoid exception happen.

Closes-Bug: #1475164
Change-Id: I7d07f657908b26fbd7ba245a9138a5dc613b4938